name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check tag
        run: |
          regex="[0-9]+\.[0-9]+\.[0-9]+"
          if [[ "${{ github.event.release.tag_name }}" =~ $regex ]]; then
            echo "Tag is valid"
          else
            echo "Tag invalid!"
            exit 1
          fi
      - name: Print and set version
        run: |
          echo "tag: ${{ github.event.release.tag_name }}"
          sed -i 's/<Version>1.0.0<\/Version>/<Version>${{ github.event.release.tag_name }}<\/Version>/g' SampleVersionedLib/SampleVersionedLib.csproj
          cat SampleVersionedLib/SampleVersionedLib.csproj
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Build
        run: dotnet build
      - name: Pack
        run: |
          dotnet pack SampleVersionedLib/SampleVersionedLib.csproj --output out
          zip -r release.zip out
      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
