name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print info
        run: |
          echo "ref: ${{ github.ref_name }}"
          echo "tag: ${{ github.event.release.tag_name }}"
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
